### ISSUE TITLE
При открытии файла в имени файла место пустоты появляется "openFileDialog1"

### ISSUE THREAD

**Issue by alexsyw** [veselcraft/VeNote#1]
# При открытии файла в имени файла место пустоты появляется "openFileDialog1"
Заходим в приложение, затем в меню выберем открытие приложения. Вуаля, баг работает. (п.с баг работает даже в быстром меню)

![explorer_2018-02-07_19-25-01](https://user-images.githubusercontent.com/33035109/35927859-cab677e8-0c3c-11e8-9eee-b134f9feb8de.png)

OS: Windows 7 x64 [Russian]
VER: VeNote 3.0 alpha

**Comment by veselcraft** [comment]
Будет исправлено в следующих обновлениях

**Comment by alexsyw** [comment]
Сяб ;)
